name: SLM Validate

on:
  workflow_dispatch:
  push:
    paths:
      - 'download.sh'
      - 'main.py'
      - 'scripts/**'
      - 'data/**'
      - 'requirements.txt'
      - '.github/workflows/slm-validate.yml'

concurrency:
  group: slm-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed only if you want to commit README/artifacts back

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install -U llama-cpp-python rich
          fi

      - name: Cache models
        uses: actions/cache@v4
        with:
          path: models
          key: models-${{ hashFiles('download.sh') }}

      - name: Run download.sh
        run: |
          chmod +x download.sh
          ./download.sh

      - name: Run main.py (batch)
        run: |
          set -e
          mkdir -p runs
          # Try to detect the first GGUF downloaded by download.sh
          MODEL_PATH="${MODEL_PATH:-$(ls -1 models/*.gguf 2>/dev/null | head -n1)}"
          if [ -z "$MODEL_PATH" ]; then
            echo "No .gguf model found in ./models. Set MODEL_PATH or make download.sh put a file there." >&2
            exit 1
          fi

          # If you have a JSONL dataset, keep this; otherwise switch to --try-defaults
          if [ -f data/input.jsonl ]; then
            python main.py \
              --model "$MODEL_PATH" \
              --input-jsonl data/input.jsonl \
              --output-jsonl runs/out.jsonl \
              --out-csv runs/out.csv \
              --quiet-batch
          else
            echo "data/input.jsonl not found; running built-in defaults."
            python main.py \
              --model "$MODEL_PATH" \
              --try-defaults \
              --print-one-line | tee runs/out.jsonl
            # create a minimal CSV too
            echo 'id,specificity,detail,usability,clarity,completeness,relevance,canonical_json,question,answer' > runs/out.csv
          fi

      - name: Generate README from JSONL
        run: |
          set -e
          # Prefer an executable script; fall back to Python names
          if [ -x scripts/jsonl_to_readmewo ]; then
            scripts/jsonl_to_readmewo runs/out.jsonl > README.md
          elif [ -f scripts/jsonl_to_readmewo.py ]; then
            python scripts/jsonl_to_readmewo.py runs/out.jsonl > README.md
          elif [ -f scripts/jsonl_to_readme.py ]; then
            python scripts/jsonl_to_readme.py runs/out.jsonl > README.md
          else
            echo "Converter script not found (scripts/jsonl_to_readmewo[.py] or jsonl_to_readme.py)." >&2
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: slm-results
          path: |
            runs/out.jsonl
            runs/out.csv
            README.md

      # Optional: auto-commit README & outputs back to the repo
      - name: Commit README (optional)
        if: ${{ success() }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: update README from JSONL"
          file_pattern: README.md runs/out.jsonl runs/out.csv
